print("Hello world")
print(3)
print(0)
print(23.3)
print("Python")
print("")
print(-3)
print("hello everyone, i am learing python")
print("hello everyone\ni am learing python")
print(True)
print(False)